[package]
name = "clap-sort"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
include = ["src/**/*.rs", "Cargo.toml"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "visit"] }
